### ISSUE TITLE
 trouble with my css

### ISSUE THREAD

**Issue by khaas2002** [1718-pawd07/p04-girldevelopit-khaas2002#1]
My CSS is all messed up and idk what to do to fix it. mainly the fonts and background color

**Comment by ms-marinelli** [comment]
It looks like the CSS that you used for C11, so you'll need to do some updating. These are the things that I noticed. I know this seems like a lot, but just take it one section at a time. I'm unavailable after school today (4/24) but you're more than welcome to stop by during Flex tomorrow (4/25) (or we can come up w/another date that works). 

General CSS Comments:
- [ ] remove unnecessary/unused styles; you have rules for `h1-h6`, yet you are only using `<h1>` and `<h3>` in your HTML

Fonts/Text (use `font-family` property):
- [ ] headers should be in a cursive font
- [ ] main content should be in a sans-serif font
- [ ] footer content should be in a serif font
- [ ] use `text-decoration` to underline your headings

Background Colors:
- [ ] set background color for `header` section 
- [ ] set background color for `body` section

Links:
- [ ] links should appear using the default link styles for unvisited and visited links (you only need to define link styles for `a:hover` and `a:focus`)
- [ ] the link text font-size should get bigger when you hover or focus
- [ ] the text color should change to a darker pink when you hover or focus

Photos:
- [ ] try using a class to `float` the two images in the main section to the right
- [ ] remove `height` and `width` for pictures from your HTML
- [ ] try using `text-align` for the `header` section CSS rule to center your logo
